#frps服务端公网IP
serverAddr = "88.88.88.88"
#frps服务端公网端口
serverPort = 8888
#连接服务端的超时时间（增大时间避免frpc在网络未就绪的情况下启动失败）
transport.dialServerTimeout = 60
#第一次登陆失败后是否退出
loginFailExit = false
#可选，建议启用
auth.method = "token"
auth.token = "88888888"

#[二选一即可]每台机器的 name 和 remotePort 不可重复，通过 http://88.88.88.88:5000 访问
[[proxies]]
#同一个frps下，多台设备的 name 不可重复
name = "SmsForwarder-TCP-001"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5000
#只要修改下面这一行（frps所在服务器必须暴露且防火墙放行的公网端口，同一个frps下不可重复）
remotePort = 5000

#[二选一即可]每台机器的 name 和 customDomains 不可重复，通过 http://smsf.demo.com 访问
[[proxies]]
#同一个frps下，多台设备的 name 不可重复
name = "SmsForwarder-HTTP-001"
type = "http"
localPort = 5000
#只要修改下面这一行（在frps端将域名反代到vhost_http_port）
customDomains = ["smsf.demo.com"]
